engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    exclude_patterns:
      - "app/javascript/clientIdPage/ClientIdPage.test.js"
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true 
    channel: "eslint-4"
    config:
      config: './.eslintrc-codeclimate.js'
  fixme:
    enabled: true
  flog:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-48
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.js"
  - "**.jsx"
exclude_paths:
- karma.conf.js
- config/
- db/
- vendor/
- app/assets
- bin/
- test/
