version: '3.2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
      build: .
      volumes:
        - type: bind
          source: ./app
          target: /app/app
      ports:
        - "3000:3000"
        - "3035:3035"
      command: ['foreman', 'start', '-f', 'Procfile.dev.docker']
      depends_on:
        - redis
